global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'solace-metrics'
    static_configs:
      - targets: ['solace-exporter:9628']   # container name + exporter port
    metrics_path: /metrics
  
  - job_name: 'solace-std'
    scrape_interval: 15s
    metrics_path: /solace-std
    static_configs:
    - targets:
      - https://admin:admin@solace:943
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: solace-exporter:9628