apiVersion: 1

datasources:
- name: Solace
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  password:
  user:
  database:
  basicAuth: false
  basicAuthUser:
  basicAuthPassword:
  withCredentials:
  isDefault: true
  jsonData:
     pdcInjected: false
  version: 1
  editable: true